name: opsdroid-desktop # you probably want to 'snapcraft register <name>'
version: '0.2.7' # just for humans, typically '1.2+git' or '1.3.2'
summary: A desktop application for Opsdroid 
description: |
  A cross-platform electron (https://electron.atom.io/) and react 
  (https://facebook.github.io/react/) desktop app for chatting with opsdroid
  (https://github.com/opsdroid/opsdroid).
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  opsdroid-desktop:
    command: opsdroid-desktop

parts:
  opsdroid-desktop:
    # See 'snapcraft plugins'
    plugin: nodejs
